#ifndef PWM_H
#define PWM_H

#include <stdbool.h>
#include <stdint.h>

#ifndef OEW_BENCH_APERTURE
#define OEW_BENCH_APERTURE 0
#endif

/* Context paired atomically with the next TIM1 TRGO / injected frame. A true
 * value proves a measured 6×2 reconstruction window; it is never a generic
 * “ADC enabled” indication. */
typedef struct {
    uint8_t sector;       /* measured-map sector: 0..5 */
    uint8_t window;       /* measured-map window: 0..1 */
    bool valid;           /* only true for an admitted, measured context */
} PwmSampleContext;

/* Immutable service pattern supplied only by the map-capture profile layer.
 * The service path always publishes context.valid=false because the mapping is
 * deliberately being measured. */
typedef struct {
    uint16_t tim1_ccr[3];
    uint16_t tim8_ccr[3];
    uint8_t sector_candidate;
    uint8_t window_candidate;
    uint32_t trigger_revision;
} PwmServiceCapturePattern;

enum {
    PWM_ENABLE_OK                       =  0,
    PWM_ENABLE_FAULT_LATCHED            = -1,
    PWM_ENABLE_CLOCK_FAILED             = -2,
    PWM_ENABLE_CONTEXT_INVALID          = -3,
    PWM_ENABLE_INTERLOCK_OPEN           = -4,
    PWM_ENABLE_ADC_NOT_ARMED            = -5,
    PWM_ENABLE_SERVICE_PROFILE_REQUIRED = -6,
    PWM_ENABLE_SERVICE_PATTERN_INVALID  = -7,
    PWM_ENABLE_ALREADY_ACTIVE           = -8
};

void PWM_Init(void);

/* Normal FOC/Vf control path. CCR preloads and sample context are one
 * transaction; no update event is generated by this function. */
bool PWM_SetControlVector(int16_t mu, int16_t mv, int16_t mw,
                          const PwmSampleContext *context);
bool PWM_GetPendingSampleContext(PwmSampleContext *out);
bool PWM_HasValidSampleContext(void);
void PWM_InvalidateSampleContext(void);

/* Compatibility/service APIs. They invalidate context and cannot arm PWM. */
void PWM_SetMod1(int16_t mu, int16_t mv, int16_t mw);
void PWM_SetMod2(int16_t mu, int16_t mv, int16_t mw);
void PWM_SetDuty1(uint16_t u, uint16_t v, uint16_t w);
void PWM_SetDuty2(uint16_t u, uint16_t v, uint16_t w);

/* Normal path: requires valid reconstruction context, injected ADC master,
 * no central fault, good clock and verified direct-SD physical interlock. */
int PWM_Enable(void);

/* Bounded map-capture service path. This is the only PWM entry point that may
 * start an unverified diagnostic aperture. It never enables control admission
 * and it requires the same direct-SD hardware interlock as normal PWM. */
int PWM_ServiceCaptureStart(const PwmServiceCapturePattern *pattern);

/* Legacy API intentionally cannot energise the direct-SD power stage. */
int PWM_ServiceEnable(const PwmSampleContext *context);

/* Central terminal stop. It stops timers/MOE, centres CCR, invalidates the
 * aperture and stops the injected ADC master. No external ARM path exists. */
void PWM_Disable(void);
uint32_t PWM_IsEnabled(void);

/* Read-only physical safety gate. The result is false unless the build has
 * OEW_HS1_COMMISSIONING_RELEASE=1 and both direct SD lines plus timer state
 * agree. The terminal latch lives in the central PROTECT fault; BIF stays
 * set until the break ISR clears it, so a pending break blocks interlock. */
bool PWM_HardwareInterlockHealthy(void);
bool PWM_BreakFaultActive(void);

void PWM_SetDeadTimeComp(int32_t dt_ticks);
uint16_t PWM_GetARR(void);
int PWM_SetDeadTime_ns(uint32_t dt_ns);
uint32_t PWM_GetDeadTime_ns(void);
void PWM_GetStatus(uint32_t *cr1, uint32_t *ccer, uint32_t *bdtr, uint32_t *cnt);
void PWM_GetSysInfo(uint32_t *psc, uint32_t *tclk);
void PWM_DumpRegs8(uint32_t *psc, uint32_t *arr, uint32_t *bdtr,
                   uint32_t *cr1, uint32_t *cr2, uint32_t *ccer);
void PWM_DumpRegs(uint32_t *psc, uint32_t *arr, uint32_t *bdtr,
                  uint32_t *cr1, uint32_t *cr2, uint32_t *ccer);

/* Retained only for source compatibility. The replacement never lets this
 * legacy debug API enable CEN or MOE. */
void PWM_DebugSetModulation(uint16_t arr, uint16_t mod_pct,
                            uint32_t dt_ns, uint8_t mask);

#if OEW_BENCH_APERTURE
/* No-output bench instrumentation. Timer counters may run only to expose
 * TRGO/ADC timing; PWM output enables and MOE are forced low in every path. */
int  PWM_BenchApertureStart(uint16_t arr, uint16_t ccr_u,
                            uint16_t ccr_v, uint16_t ccr_w);
int  PWM_BenchApertureSetVector(uint16_t ccr_u, uint16_t ccr_v,
                                uint16_t ccr_w);
void PWM_BenchApertureStop(void);
#endif


/* Align-check aperture (docs/TZ_ALIGN_CHECK_AND_TWO_GATE_FIRST_START_PC3.md,
 * report-only driverAlign recipe). Starts TIM1+TIM8 center-aligned (5 kHz like
 * production) and raises MOE only for the single static differential vector
 * set by PWM_AlignApertureSetVector, behind the same admission gate as
 * PWM_Enable (PROTECT fault, clock fail, hardware interlock, ADC arming),
 * re-verified after MOE. No control loop, no angle source, CCRs never move on
 * their own: the rotor stays stationary and the operator reads @ADC I1/I2
 * through the normal CLI. */
#define PWM_ALIGN_MAX_CCR_DELTA 96u   /* ~10% modulation at ARR=999 */
int  PWM_AlignApertureStart(uint16_t arr);
int  PWM_AlignApertureSetVector(uint16_t tim1_ccr[3], uint16_t tim8_ccr[3]);
void PWM_AlignApertureStop(void);

#endif /* PWM_H */
