#ifndef PWM_H
#define PWM_H

#include <stdbool.h>
#include <stdint.h>

/* Context paired atomically with the next TIM1 TRGO / injected frame. A true
 * value proves a measured 6×2 reconstruction window; it is never a generic
 * “ADC enabled” indication. */
typedef struct {
    uint8_t sector;       /* measured-map sector: 0..5 */
    uint8_t window;       /* measured-map window: 0..1 */
    bool valid;           /* only true for an admitted, measured context */
} PwmSampleContext;

/* Immutable service pattern supplied only by the map-capture profile layer.
 * The service path always publishes context.valid=false because the mapping is
 * deliberately being measured. */
typedef struct {
    uint16_t tim1_ccr[3];
    uint16_t tim8_ccr[3];
    uint8_t sector_candidate;
    uint8_t window_candidate;
    uint32_t trigger_revision;
} PwmServiceCapturePattern;

enum {
    PWM_ENABLE_OK                       =  0,
    PWM_ENABLE_FAULT_LATCHED            = -1,
    PWM_ENABLE_CLOCK_FAILED             = -2,
    PWM_ENABLE_CONTEXT_INVALID          = -3,
    PWM_ENABLE_INTERLOCK_OPEN           = -4,
    PWM_ENABLE_ADC_NOT_ARMED            = -5,
    PWM_ENABLE_SERVICE_PROFILE_REQUIRED = -6,
    PWM_ENABLE_SERVICE_PATTERN_INVALID  = -7,
    PWM_ENABLE_ALREADY_ACTIVE           = -8
};

void PWM_Init(void);

/* Normal FOC/Vf control path. CCR preloads and sample context are one
 * transaction; no update event is generated by this function. */
bool PWM_SetControlVector(int16_t mu, int16_t mv, int16_t mw,
                          const PwmSampleContext *context);
bool PWM_GetPendingSampleContext(PwmSampleContext *out);
bool PWM_HasValidSampleContext(void);
void PWM_InvalidateSampleContext(void);

/* Compatibility/service APIs. They invalidate context and cannot arm PWM. */
void PWM_SetMod1(int16_t mu, int16_t mv, int16_t mw);
void PWM_SetMod2(int16_t mu, int16_t mv, int16_t mw);
void PWM_SetDuty1(uint16_t u, uint16_t v, uint16_t w);
void PWM_SetDuty2(uint16_t u, uint16_t v, uint16_t w);

/* Normal path: requires valid reconstruction context, injected ADC master,
 * no central fault, good clock and verified OEW-HS-1 physical interlock. */
int PWM_Enable(void);

/* Bounded map-capture service path. This is the only PWM entry point that may
 * start an unverified diagnostic aperture. It never enables control admission
 * and it requires the same OEW-HS-1 hardware interlock as normal PWM. */
int PWM_ServiceCaptureStart(const PwmServiceCapturePattern *pattern);

/* Legacy API intentionally cannot energise the OEW-HS-1 power stage. */
int PWM_ServiceEnable(const PwmSampleContext *context);

/* Central terminal stop. It drops ARM_REQ before stopping timers/MOE, centres
 * CCR, invalidates aperture and stops the injected ADC master. */
void PWM_Disable(void);
uint32_t PWM_IsEnabled(void);

/* Read-only physical safety gate. The result is false unless the build has
 * OEW_HS1_COMMISSIONING_RELEASE=1 and PB11/PB12/PD2 + timer state agree. */
bool PWM_HardwareInterlockHealthy(void);
bool PWM_BreakFaultActive(void);

/* Foreground health owner toggles PB13 at a separately reviewed cadence. This
 * function never grants PWM permission and must not be called from ADC ISR. */
void PWM_HeartbeatToggle(void);

void PWM_SetDeadTimeComp(int32_t dt_ticks);
uint16_t PWM_GetARR(void);
int PWM_SetDeadTime_ns(uint32_t dt_ns);
uint32_t PWM_GetDeadTime_ns(void);
void PWM_GetStatus(uint32_t *cr1, uint32_t *ccer, uint32_t *bdtr, uint32_t *cnt);
void PWM_GetSysInfo(uint32_t *psc, uint32_t *tclk);
void PWM_DumpRegs8(uint32_t *psc, uint32_t *arr, uint32_t *bdtr,
                   uint32_t *cr1, uint32_t *cr2, uint32_t *ccer);
void PWM_DumpRegs(uint32_t *psc, uint32_t *arr, uint32_t *bdtr,
                  uint32_t *cr1, uint32_t *cr2, uint32_t *ccer);

/* Retained only for source compatibility. The replacement never lets this
 * legacy debug API enable CEN, MOE or ARM_REQ. */
void PWM_DebugSetModulation(uint16_t arr, uint16_t mod_pct,
                            uint32_t dt_ns, uint8_t mask);

#endif /* PWM_H */
